//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PE.DotRasExtended.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PE.DotRasExtended.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   conf.toml に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ConfigTomlFileName {
            get {
                return ResourceManager.GetString("ConfigTomlFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   不明なエラーが発生しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorMessage001 {
            get {
                return ResourceManager.GetString("ErrorMessage001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   L2TPを使用したVPN接続が可能なデバイスが見つかりません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorMessage002 {
            get {
                return ResourceManager.GetString("ErrorMessage002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   同じ名前のVPN接続が既に存在しています。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorMessage003 {
            get {
                return ResourceManager.GetString("ErrorMessage003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   接続に失敗しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorMessage004 {
            get {
                return ResourceManager.GetString("ErrorMessage004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   接続を登録できませんでした。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorMessage005 {
            get {
                return ResourceManager.GetString("ErrorMessage005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   VPN設定は既に初期化済みです。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorMessage006 {
            get {
                return ResourceManager.GetString("ErrorMessage006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   接続を登録しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string InfoMessage001 {
            get {
                return ResourceManager.GetString("InfoMessage001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   接続に成功しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string InfoMessage002 {
            get {
                return ResourceManager.GetString("InfoMessage002", resourceCulture);
            }
        }
    }
}
